[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "physiotrack"
version = "0.1.0"
description = "Python library for detection and pose estimation using a variety of state-of-the-art models like YOLO, RT-DETR, Sapiens, and ViTPose. The framework supports modular detection and pose pipelines with validated models for specialized tasks like VR student monitoring, face detection, and whole-body pose estimation"
readme = "README.md"
license = { "text" = "GPL-3.0 license" }
authors = [
  { name = "Tharindu Ekanayake", email = "physiotrack@gmail.com" }
]

[project.optional-dependencies]
docs = [
  "mkdocs>=1.6,<2",
  "mkdocs-material>=9.5",
  "mkdocstrings[python]>=0.24",
  "mkdocs-autorefs>=1.0",
  "pymdown-extensions>=10",
]
test = [
  "pytest>=7",
  "numpy",
  "scipy",
  "pandas",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"
filterwarnings = [
  "ignore::DeprecationWarning",
  "ignore::RuntimeWarning",
]

[project.urls]
"Homepage" = "https://github.com/physiotrack/physiotrack"
"Documentation" = "https://tharindu326.github.io/physiotrack/"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
physiotrack = ["assets/fonts/*.ttf"]
